---
- name: Restart Postfix
  service:
    name: postfix
    state: restarted

- name: Restart Amavisd
  service:
    name: amavis
    state: restarted

- name: Restart Dovecot
  service:
    name: dovecort
    state: restarted

- name: Reload newaliases
  shell: newaliases
