---
- name: Restart OpenVPN server
  systemd:
    name: openvpn-server@server
    state: restarted
    daemon_reload: yes

- name: Reload UFW
  ufw:
    state: reloaded

- name: Save iptables rules
  command: netfilter-persistent save

