---
- name: Install letsencrypt client
  apt:
    name: python-certbot-apache
    state: latest

- name: Create related directories
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - "/etc/{{ apache_distro_name }}/cert"

- name: Create letsencrypt certificate
  shell: >
    letsencrypt -n --apache -w {{ http_document_root }} -m {{ letsencrypt_email }} \
      --agree-tos -d {{ http_domain_name }} -d www.{{ http_domain_name }} --redirect
  args:
    creates: "/etc/letsencrypt/live/{{ http_domain_name }}"

- name: Generate dhparams
  shell: "openssl dhparam -out /etc/{{ apache_distro_name }}/cert/dhparams.pem 2048"
  args:
    creates: "/etc/{{ apache_distro_name }}/cert/dhparams.pem"

- name: Add letsencrypt cronjob for certificate renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: >-
      letsencrypt certonly -n --apache -w {{ http_document_root }} -m {{ letsencrypt_email }}
      --agree-tos -d {{ http_domain_name }} -d www.{{ http_domain_name }} && systemctl reload apache2
