---
# Install these extra yum packages
bbb_lxc_host_packages:
  - lxc-templates
  - lxc-utils
  - net-tools

# This is the name of LXC profile that should be used for all BBB LXC instances
bbb_lxc_profile: bbb_macvlan

# Mount point for extra LXC storage volume mounted within the container. If empty storage volume will not be created.
bbb_lxc_storage_shared: /opt/bbbshared

# The name of local network used for communication between containers directly. If empty network will not be created.
bbb_lxc_bridged_network: ''

# Default profile storage pool name for directory root.
bbb_lxc_storage_pool_default: default

# Storage pool name used for storage volume for BigBlueButton files
bbb_lxc_storage_pool: bigbluebutton

# Host OS path where LXC storage pool is created. Leave empty and role will not create new storage pool.
bbb_lxc_storage_pool_dir: ''
