---
- name: Ensure the guest user is removed
  rabbitmq_user:
    user: guest
    state: absent

- name: Add RabbitMQ users
  rabbitmq_user:
      user: "{{item.user}}"
      password: "{{item.password}}"
      configure_priv: "{{item.configure_priv|default('.*')}}"
      read_priv: "{{item.read_priv|default('.*')}}"
      write_priv: "{{item.write_priv|default('.*')}}"
      vhost: "{{item.vhost|default('/')}}"
      tags: "{{item.tags|default('')}}"
  with_items: "{{ rabbitmq_users }}"

- name: Enable RabbitMQ plugins
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
    prefix: /usr/lib/rabbitmq
  with_items: "{{ rabbitmq_plugins }}"
  notify: Restart RabbitMQ server
