---
# URL path to official BBB bash install script
bbb_lxc_bbb_install_url: 'https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh'
# If set BBB will automatically redirect user to this url for default document root
bbb_lxc_bbb_redirect_url:
# Path of index file for default document root
# Uncomment for BBB lower than v2.4: bbb_lxc_bbb_index_file: '/var/www/bigbluebutton-default/index.html'
bbb_lxc_bbb_index_file: '/var/www/bigbluebutton-default/assets/index.html'
# Path to BBB properties file
bbb_lxc_bbb_properties_file: '/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties'
# Path to Freeswitch configuration
bbb_lxc_bbb_freeswitch_config_file: '/opt/freeswitch/etc/freeswitch/vars.xml'
# Target systemd unit directory
bbb_lxc_systemd_unit_dir: '/usr/lib/systemd/system'
# Path to HTML5 systemd unit file
bbb_lxc_bbb_html5unit_file: '{{ bbb_lxc_systemd_unit_dir }}/bbb-html5.service'
# If true container will be configured for local network
bbb_lxc_net_bridged: true
# If true role will force BBB install script even if BBB has already been installed
bbb_lxc_force_bbb_install: false
# Adjust CPU and scheduling policy for systemd units to prevent errors when running in LXC
bbb_systemd_containerize_units: true
# Temporary directory to use on host OS for template processing
bbb_lxc_tmp_dir: /tmp
# If true recordings will be processed only out of working hours
bbb_lxc_recording_timer_enabled: false
# Path to recording timer file for systemd scheduling
bbb_lxc_recording_timer_file: /etc/systemd/system/bbb-record-core.timer.d/override.conf
# If true multiple kurentos instances will be configured via BBB install script
bbb_lxc_multiple_kurentos: true
# Optional HTML5 document title to shot in browser
bbb_lxc_html5_title: ''
# Set URL for collecting HTML5 client logs
bbb_lxc_html5_external_debug_url: ''
# Path to BBB shared directory
bbb_lxc_shared_dir: /opt/bbbshared/instances
# Path to playbook local directory where default slides are located
bbb_lxc_local_slides_dir: '{{ playbook_dir }}/../files/bbb'
# Array of default slide files to copy to BBB configuration
bbb_lxc_local_slides:
  - 'default.pptx'
  - 'default.pdf'

# Install Filebeat agent, unless disabled on instance config
bbb_lxc_install_filebeat: true
# Logstash URL that will be used as Filebeat output
bbb_lxc_filebeat_logstash_url:
# Default Filebeat input include_lines pattern
bbb_lxc_filebeat_include_pattern: '(ERR|WARN|error|warn|warning|critical|urgent|fail|exception)'
# Default Filebeat certificates directory
bbb_lxc_filebeat_cert_dir: /etc/filebeat/certs
# Local CA certificate file
# More info on how to setup certs for logstash can be found here (you can use same tutorial for filebeat client certs)
# https://kifarunix.com/easy-way-to-configure-filebeat-logstash-ssl-tls-connection/
bbb_lxc_filebeat_cacert: ''
# Local Certificate file
bbb_lxc_filebeat_clientcert: ''
# Local private key file
bbb_lxc_filebeat_clientkey: ''

# Install prometheus node exporter, unless disabled on instance config
bbb_lxc_install_node_exporter: true

# BBB node exporter docker directory
bbb_lxc_node_exporter_dir: /opt/bbb_node_exporter

# BBB node exporter nginx config file
bbb_lxc_node_exporter_nginx_config: '{{ bbb_lxc_node_exporter_dir}}/nginx_prometheus_node_exporter.conf'

# Username and password for Prometheus HTTP authentication
bbb_lxc_node_exporter_user: bbb_prometheus
bbb_lxc_node_exporter_pass:

# Limit node_exporter nginx proxy to allow only requests from this ip address
bbb_lxc_node_exporter_ip_address:

# Defines a hostname for turn/turns server
bbb_lxc_turn_server:
# Turn/turns server secret
bbb_lxc_turn_secret:
# Path to BBB stun-turn configuration file
bbb_lxc_turn_config_file: /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

# List of default yum packages to install on BBB LXC instance
bbb_lxc_default_packages:
  - vim
  - git
  - tree
  - screen
  - htop
  - telnet
  - unattended-upgrades
  - nmap
  - etckeeper
  - net-tools
  - stress
  - bc

# List of LXC instances. See example bellow.
bbb_lxc_instances: []
#  - name: bbbmeet
#    hostname:
#    email:
#    ip_address:
#    network_ip:
#    net_mask:
#    broadcast:
#    install_bbb: false
#    default_route:
#    dns_servers:
#    profile:
#    image:
#    install_node_exporter:
