---
- name: Install bash auto-completions
  apt:
    name: bash-completion
    state: present

- name: Copy root user's bash aliases
  template:
    src: root.bash_aliases.j2
    dest: /root/.bash_aliases
    mode: 0644
    owner: root
    group: root

- name: "Prevent direct SSH login for root"
  lineinfile:
    dest: /etc/ssh/sshd_config
    insertafter: "{{ item.after }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - after: '^#?PermitRootLogin'
      line: 'PermitRootLogin prohibit-password'
  notify: Restart SSHD service

- name: "Prevent direct SSH login for {{ app_user }} user"
  lineinfile:
    dest: /etc/ssh/sshd_config
    insertafter: "{{ item.after }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - after: '^#DenyUsers'
      line: "DenyUsers {{ app_user }}"
  when: app_user is defined
  notify: Restart SSHD service

- name: Enable UFW and allow SSH only
  ufw:
    rule: limit
    port: ssh
    proto: tcp
    default: deny
    state: enabled
  notify: Restart UFW firewall service

- name: Configure hostname
  hostname:
    name: "{{ server_hostname }}"
  when: server_hostname != ""

- name: Configure default CRON email
  lineinfile:
    dest: /etc/crontab
    insertbefore: '^SHELL='
    line: 'MAILTO=root'
    state: present

- name: Configure inputrc
  lineinfile:
    dest: /etc/inputrc
    insertbefore: "^#.+?: {{ item.cmd }}"
    line: "{{ item.code }}: {{ item.cmd }}"
    state: present
  with_items:
    - cmd: history-search-backward
      code: '"\e[5~"'
    - cmd: history-search-forward
      code: '"\e[6~"'
