---
- name: Setup locale
  lineinfile:
    dest: /etc/environment
    line: 'LC_ALL=en_US.UTF-8'
    state: present

- include_tasks: install_packages.yml
- include_tasks: configure_environment.yml
- include_tasks: configure_user.yml
  when: app_user is defined and admin_user is defined

- include_tasks: configure_autoupdates.yml
  when: unattended_upgrades_enable
