---

- name: Healthcheck LXD instances
  include_tasks: bbb/check_instance.yml
  loop: '{{ bbb_lxc_instances }}'
  when: lxc_instance.install_bbb|default(false)
  loop_control:
    loop_var: lxc_instance
    label: "{{ lxc_instance.name }} - {{ lxc_instance.hostname }}"
