---

- name: Install apt packages
  command:
    cmd: 'lxc exec {{ lxc_instance.name }} -- apt-get {{ item }}'
  with_items:
    - 'update'
    - 'install apt-transport-https ca-certificates curl gnupg'

- name: Install docker repository keyring
  shell: 'lxc exec {{ lxc_instance.name }} -- sh -c "{{ item }}"'
  with_items:
    - "rm /usr/share/keyrings/docker-archive-keyring.gpg || echo 'Docker keyring does not exist locally'"
    - 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'

- command:
    cmd: 'lxc exec {{ lxc_instance.name }} -- grep download.docker.com /etc/apt/sources.list.d/docker.list'
  register: apt_docker_repo_exists
  ignore_errors: true

- name: Install docker repository
  shell: >-
    lxc exec {{ lxc_instance.name }} -- sh -c
    'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  when: apt_docker_repo_exists.rc != 0

- name: Install apt packages
  command:
    cmd: 'lxc exec {{ lxc_instance.name }} -- apt-get {{ item }}'
  with_items:
    - 'update'
    - 'install docker-ce docker-ce-cli containerd.io -y'

- command:
    cmd: 'lxc exec {{ lxc_instance.name }} -- ls /usr/local/bin/docker-compose'
  register: bbb_scalelite_docker_composer_exists
  ignore_errors: true

- name: Install docker compose
  command:
    cmd: "lxc exec {{ lxc_instance.name }} -- sh -c '{{ item }}'"
  with_items:
    - 'curl -L https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose'
    - 'chmod +x /usr/local/bin/docker-compose'
  when: bbb_scalelite_docker_composer_exists.rc != 0

- command:
    cmd: 'lxc exec {{ lxc_instance.name }} -- ls {{ bbb_scalelite_dir }}'
  register: bbb_scalelite_run_exists
  ignore_errors: true
