---

- name: '{{ lxc_instance.name }}: Install apt packages'
  command:
    cmd: 'lxc exec {{ lxc_instance.name }} -- apt-get {{ item }}'
  with_items:
    - 'update -y'
    - 'install apt-transport-https ca-certificates curl gnupg -y --force-yes'

- name: '{{ lxc_instance.name }}: Install docker repository keyring'
  shell: 'lxc exec {{ lxc_instance.name }} -- sh -c "{{ item }}"'
  with_items:
    - "rm /usr/share/keyrings/docker-archive-keyring.gpg || echo 'Docker keyring does not exist locally'"
    - 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'

- command:
    cmd: 'lxc exec {{ lxc_instance.name }} -- grep download.docker.com /etc/apt/sources.list.d/docker.list'
  register: apt_docker_repo_exists
  ignore_errors: true

- name: '{{ lxc_instance.name }}: Install docker repository'
  shell: >-
    lxc exec {{ lxc_instance.name }} -- sh -c
    'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  when: apt_docker_repo_exists.rc != 0

- name: '{{ lxc_instance.name }}: Install apt packages'
  command:
    cmd: 'lxc exec {{ lxc_instance.name }} -- apt-get {{ item }}'
  with_items:
    - 'update'
    - 'install docker-ce docker-ce-cli containerd.io -y'

