---

- name: Detect default ethernet interface
  shell: 'ip route show default 0.0.0.0/0 | cut -d" " -f5'
  register: stat_default_route_iface

- fail:
    msg: 'Could not determine default route network interface'
  when: not stat_default_route_iface.stdout|length

- set_fact:
    default_route_iface: '{{ stat_default_route_iface.stdout }}'

- name: Create LXD instances
  include_tasks: create_instance.yml
  loop: '{{ bbb_lxc_instances }}'
  loop_control:
    loop_var: lxc_instance

- name: Install docker in LXC instances
  include_tasks: install_docker.yml
  loop: '{{ bbb_lxc_instances }}'
  when: lxc_instance.install_docker | default(bbb_lxc_install_docker)
  loop_control:
    loop_var: lxc_instance

- name: Configure nightly docker maintenance (docker prune)
  include_tasks: install_docker_prune_cron.yml
  loop: '{{ bbb_lxc_instances }}'
  loop_control:
    loop_var: lxc_instance

- include_tasks: install_bbb_instances.yml

- include_tasks: install_node_exporter_instances.yml

- include_tasks: install_filebeat_instances.yml
