---
- name: Install memcached
  apt:
    name: memcached
    state: latest
  when: not is_rhel

- name: Install memcached
  yum:
    name: memcached
    state: latest
  when: is_rhel

- name: Start memcached
  service:
    name: memcached
    state: started
    enabled: true
